CREATE TABLE USERS
(
    USER_ID                 INT8         NOT NULL,
    USERNAME                VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD                VARCHAR(150) NOT NULL,
    PASSWORD_CONFIRMATION   VARCHAR(150) NULL,
    ENABLED                 BOOLEAN      NOT NULL,
    ACCOUNT_NON_EXPIRED     BOOLEAN,
    ACCOUNT_NON_LOCKED      BOOLEAN,
    CREDENTIALS_NON_EXPIRED BOOLEAN,
    CREATED_DATE            TIMESTAMP,
    LAST_UPDATED_DATE       TIMESTAMP,
    EMAIL                   VARCHAR(150) UNIQUE,
    MOBILE_NO               VARCHAR(150),
    PASSWORD_RESET          BOOLEAN NOT NULL,
    CONSTRAINT USERNAME_PK PRIMARY KEY (USERNAME)
);

CREATE TABLE USER_AUTH_GROUP
(
    USER_AUTH_GROUP_ID INT8        NOT NULL,
    USERNAME           VARCHAR(50) NOT NULL,
    AUTH_GROUP         VARCHAR(50) NOT NULL,
    CONSTRAINT USERNAME_FK FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);

CREATE SEQUENCE USER_SEQUENCE START WITH 50 INCREMENT BY 1;
CREATE SEQUENCE USER_AUTH_SEQUENCE START WITH 50 INCREMENT BY 1;

CREATE UNIQUE INDEX USER_AUTH_GROUP_IDX ON USER_AUTH_GROUP (USERNAME, AUTH_GROUP);