CREATE TABLE NBA_SEGMENTS
(
    SEGMENT_ID       INT8         NOT NULL,
    SEGMENT_NAME     VARCHAR(255) NOT NULL,
    SEGMENT_PRIORITY INT8         NOT NULL,
    CONSTRAINT SEGMENT_PK PRIMARY KEY (SEGMENT_ID)
);

CREATE TABLE NBA_SUB_SEGMENTS
(
    SUBSEGMENT_ID       INT8         NOT NULL,
    SEGMENT_ID       INT8         NOT NULL,
    SUBSEGMENT_NAME     VARCHAR(255) NOT NULL,
    SUBSEGMENT_PRIORITY INT8         NOT NULL,
    SUBSEGMENT_RULES TEXT,
    CONSTRAINT SEGMENT_FK FOREIGN KEY (SEGMENT_ID) REFERENCES NBA_SEGMENTS (SEGMENT_ID)
);


CREATE UNIQUE INDEX NBA_SUB_SEGMENTS_IDX ON NBA_SUB_SEGMENTS (SEGMENT_ID, SUBSEGMENT_NAME);